### PR TITLE
README update

### PR DESCRIPTION
**Pull request by joepeck28**
This is a first draft of the README for this week. Take a look and let's decide what else we want to include/omit

### CODE REVIEW

**Review by NikkoB702 — APPROVED** [review]

**Review by larabjork — APPROVED** [review]
Thanks for pulling this together, Joe! And to Nikko for writing up the thesis!

**Review by JGarza4903 — COMMENTED** [review]
Looks good! Thanks!

**Comment by JGarza4903** [comment]
Nice work on the README!!

**Review by JGarza4903 — APPROVED** [review]
Good joB!

**Pull request merged**
